project:
  type: website
  output-dir: docs

website:
  title: "Kirsten van Kessel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: work.qmd
        text: My Work

format:
  html:
    theme: united
    css: styles.css
    toc: true



